### ISSUE TITLE
Setup on  ejabberd-15.10?

### ISSUE THREAD

**Issue by eduardogoncalves** [knobo/mod_filter#2]
Hi,  ejabberd-15.10 use yml format, how to you setup it?
I create the file structure under "ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_filter" and runned "ejabberdctl module_install mod_filter" and it generates the files on "ejabberd/.ejabberd-modules/mod_filter". Then I tryed to edit ejabberd.yml and right below "access:" I added:

```
 mod_filter:
    allow: all
  mod_filter_presence:
    allow: all
  mod_filter_message:
    allow: all
  mod_filter_iq:
    allow: all
```

and in the file "ejabberd/.ejabberd-modules/mod_filter/conf/mod_filter.yml"

```
modules:
  mod_filter: {}
```

But with this, users go online but can't see each other. I think I'm having the block "mod_filter, mod_filter_presence in wrong place".

Thanks.
